version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ./zookeeper/:/home

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    build:
      context: ./broker
      dockerfile: Dockerfile-broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - ./broker/:/home

  kafkaproducer:
    image: kafkaproducer
    build:
      context: ./kafka_producer
      dockerfile: Dockerfile-producer
    container_name: kafkaproducer
    environment:
      KAFKA_BROKER: broker:9092
    volumes:
      - ./kafka_producer/:/home
    depends_on:
      - broker

  kafkaconsumer:
    image: kafkaconsumer
    build:
      context: ./kafka_consumer
      dockerfile: Dockerfile-consumer
    container_name: kafkaconsumer
    environment:
      KAFKA_BROKER: broker:9092
    hostname: kafkaconsumer
    volumes: 
      - ./kafka_consumer/:/home

